# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
       repository: 'syntest-framework/syntest-framework'
       token: ${{ secrets.SYNTEST_CI }}
       path: syntest-framework
    - uses: actions/checkout@v2
      with:
       repository: 'syntest-framework/syntest-solidity'
       token: ${{ secrets.SYNTEST_CI }}
       path: syntest-solidity
    - uses: actions/checkout@v2
      with:
        path: syntest-solidity-benchmark
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
       path: ~/.npm
       key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
         ${{ runner.OS }}-node-
         ${{ runner.OS }}-
    - name: Framework - Install Dependencies
      run: npm install
      working-directory: syntest-framework
    - name: Framework - Compile Typescript
      run: npm run tsc
      working-directory: syntest-framework
    - name: Solidity - Install Dependencies
      run: npm install
      working-directory: syntest-solidity
    - name: Solidity - Compile Typescript
      run: npm run tsc
      working-directory: syntest-solidity
    - name: Benchmark - Install Dependencies
      run: npm install
      working-directory: syntest-solidity-benchmark
    - name: Benchmark - Install Truffle globally
      run: npm install -g truffle
    - name: Benchmark - Run Truffle
      run: truffle run syntest-solidity
      working-directory: syntest-solidity-benchmark
