name: SynTest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run the pipeline on all the currently supported LTS versions and the latest version
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    # Cloning
    - uses: actions/checkout@v2
      with:
       repository: 'syntest-framework/syntest-framework'
       token: ${{ secrets.SYNTEST_CI }}
       path: syntest-framework
    - uses: actions/checkout@v2
      with:
       repository: 'syntest-framework/syntest-solidity'
       token: ${{ secrets.SYNTEST_CI }}
       path: syntest-solidity
    - uses: actions/checkout@v2
      with:
        path: syntest-solidity-benchmark
        
    # Setup
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # Caching
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
       path: ~/.npm
       key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
         ${{ runner.OS }}-node-
         ${{ runner.OS }}-
         
    # SynTest Framework
    - name: Framework - Install Dependencies
      run: npm install
      working-directory: syntest-framework
    - name: Framework - Compile Typescript
      run: npm run build
      working-directory: syntest-framework
      
    # SynTest Solidity
    - name: Solidity - Install Dependencies
      run: npm install
      working-directory: syntest-solidity
    - name: Solidity - Compile Typescript
      run: npm run build
      working-directory: syntest-solidity
      
    # Dependencies
    - name: Benchmark - Install Dependencies
      run: npm install
      working-directory: syntest-solidity-benchmark
    - name: Benchmark - Install Truffle globally
      run: npm install -g truffle
      
    # Trial run
    - name: Benchmark - Run Truffle
      run: truffle run syntest-solidity
      working-directory: syntest-solidity-benchmark
